#!/bin/bash

path=C:/Users/chib3/projects/quackstats-sba/src/main/java/uk/cbradbury/quackstats/enumerations

rm $path/Column.java

java -jar EnumCreator.jar column_meta.csv Column $path/Column.java

echo Column Enum has been updated
